# Generated by Django 5.0.2 on 2024-08-20 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_editora_cidade_editora_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="livro",
            old_name="autor",
            new_name="autores",
        ),
    ]
